# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Algorithms, Plot
from PyQt5 import QtCore, QtGui, QtWidgets

# Interface will be explained in the discussion
# Same as in main...
def buildGraph():
    graphs = {}
    file = open('cities.txt', 'r')
    cnt = 0
    for line in file:
        data = line.split(" ")
        if int(data[0]) not in graphs.keys():
            graphs[cnt] = [[int(data[1]), int(data[2])]]
            cnt += 1
        else:
            graphs[int(data[0])].append([int(data[1]), int(data[2])])
    return graphs


def heuristic(cityNum):
    # __,__ Areal, Walking
    cnt = 0
    ar = {}
    walk = {}
    data = open('heuristic.txt', 'r')
    for num, line in enumerate(data):
        if num == cityNum:
            temp = line.strip().split('/')
            for values in temp:
                nums = values.split(',')
                ar[cnt] = int(nums[0])
                walk[cnt] = int(nums[1])
                cnt += 1
            break
    return ar, walk


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 340)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 561))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QToolTip\n"
                                     "{\n"
                                     "     border: 1px solid black;\n"
                                     "     background-color: #ffa02f;\n"
                                     "     padding: 1px;\n"
                                     "     border-radius: 3px;\n"
                                     "     opacity: 100;\n"
                                     "}\n"
                                     "\n"
                                     "QWidget\n"
                                     "{\n"
                                     "    color: #b1b1b1;\n"
                                     "    background-color: #323232;\n"
                                     "}\n"
                                     "\n"
                                     "QTreeView, QListView\n"
                                     "{\n"
                                     "    background-color: silver;\n"
                                     "    margin-left: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QWidget:item:hover\n"
                                     "{\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
                                     "    color: #000000;\n"
                                     "}\n"
                                     "\n"
                                     "QWidget:item:selected\n"
                                     "{\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "}\n"
                                     "\n"
                                     "QMenuBar::item\n"
                                     "{\n"
                                     "    background: transparent;\n"
                                     "}\n"
                                     "\n"
                                     "QMenuBar::item:selected\n"
                                     "{\n"
                                     "    background: transparent;\n"
                                     "    border: 1px solid #ffaa00;\n"
                                     "}\n"
                                     "\n"
                                     "QMenuBar::item:pressed\n"
                                     "{\n"
                                     "    background: #444;\n"
                                     "    border: 1px solid #000;\n"
                                     "    background-color: QLinearGradient(\n"
                                     "        x1:0, y1:0,\n"
                                     "        x2:0, y2:1,\n"
                                     "        stop:1 #212121,\n"
                                     "        stop:0.4 #343434/*,\n"
                                     "        stop:0.2 #343434,\n"
                                     "        stop:0.1 #ffaa00*/\n"
                                     "    );\n"
                                     "    margin-bottom:-1px;\n"
                                     "    padding-bottom:1px;\n"
                                     "}\n"
                                     "\n"
                                     "QMenu\n"
                                     "{\n"
                                     "    border: 1px solid #000;\n"
                                     "}\n"
                                     "\n"
                                     "QMenu::item\n"
                                     "{\n"
                                     "    padding: 2px 20px 2px 20px;\n"
                                     "}\n"
                                     "\n"
                                     "QMenu::item:selected\n"
                                     "{\n"
                                     "    color: #000000;\n"
                                     "}\n"
                                     "\n"
                                     "QWidget:disabled\n"
                                     "{\n"
                                     "    color: #808080;\n"
                                     "    background-color: #323232;\n"
                                     "}\n"
                                     "\n"
                                     "QAbstractItemView\n"
                                     "{\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
                                     "}\n"
                                     "\n"
                                     "QWidget:focus\n"
                                     "{\n"
                                     "    /*border: 1px solid darkgray;*/\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit\n"
                                     "{\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
                                     "    padding: 1px;\n"
                                     "    border-style: solid;\n"
                                     "    border: 1px solid #1e1e1e;\n"
                                     "    border-radius: 5;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton\n"
                                     "{\n"
                                     "    color: #b1b1b1;\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                                     "    border-width: 1px;\n"
                                     "    border-color: #1e1e1e;\n"
                                     "    border-style: solid;\n"
                                     "    border-radius: 6;\n"
                                     "    padding: 3px;\n"
                                     "    font-size: 12px;\n"
                                     "    padding-left: 5px;\n"
                                     "    padding-right: 5px;\n"
                                     "    min-width: 40px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed\n"
                                     "{\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox\n"
                                     "{\n"
                                     "    selection-background-color: #ffaa00;\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                                     "    border-style: solid;\n"
                                     "    border: 1px solid #1e1e1e;\n"
                                     "    border-radius: 5;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox:hover,QPushButton:hover\n"
                                     "{\n"
                                     "    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "QComboBox:on\n"
                                     "{\n"
                                     "    padding-top: 3px;\n"
                                     "    padding-left: 4px;\n"
                                     "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                                     "    selection-background-color: #ffaa00;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox QAbstractItemView\n"
                                     "{\n"
                                     "    border: 2px solid darkgray;\n"
                                     "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox::drop-down\n"
                                     "{\n"
                                     "     subcontrol-origin: padding;\n"
                                     "     subcontrol-position: top right;\n"
                                     "     width: 15px;\n"
                                     "\n"
                                     "     border-left-width: 0px;\n"
                                     "     border-left-color: darkgray;\n"
                                     "     border-left-style: solid; /* just a single line */\n"
                                     "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                                     "     border-bottom-right-radius: 3px;\n"
                                     " }\n"
                                     "\n"
                                     "QComboBox::down-arrow\n"
                                     "{\n"
                                     "     image: url(:/dark_orange/img/down_arrow.png);\n"
                                     "}\n"
                                     "\n"
                                     "QGroupBox\n"
                                     "{\n"
                                     "    border: 1px solid darkgray;\n"
                                     "    margin-top: 10px;\n"
                                     "}\n"
                                     "\n"
                                     "QGroupBox:focus\n"
                                     "{\n"
                                     "    border: 1px solid darkgray;\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus\n"
                                     "{\n"
                                     "    border: 1px solid darkgray;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar:horizontal {\n"
                                     "     border: 1px solid #222222;\n"
                                     "     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                                     "     height: 7px;\n"
                                     "     margin: 0px 16px 0 16px;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::handle:horizontal\n"
                                     "{\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                                     "      min-height: 20px;\n"
                                     "      border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::add-line:horizontal {\n"
                                     "      border: 1px solid #1b1b19;\n"
                                     "      border-radius: 2px;\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "      width: 14px;\n"
                                     "      subcontrol-position: right;\n"
                                     "      subcontrol-origin: margin;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::sub-line:horizontal {\n"
                                     "      border: 1px solid #1b1b19;\n"
                                     "      border-radius: 2px;\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "      width: 14px;\n"
                                     "     subcontrol-position: left;\n"
                                     "     subcontrol-origin: margin;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
                                     "{\n"
                                     "      border: 1px solid black;\n"
                                     "      width: 1px;\n"
                                     "      height: 1px;\n"
                                     "      background: white;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                                     "{\n"
                                     "      background: none;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar:vertical\n"
                                     "{\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                                     "      width: 7px;\n"
                                     "      margin: 16px 0 16px 0;\n"
                                     "      border: 1px solid #222222;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::handle:vertical\n"
                                     "{\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                                     "      min-height: 20px;\n"
                                     "      border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::add-line:vertical\n"
                                     "{\n"
                                     "      border: 1px solid #1b1b19;\n"
                                     "      border-radius: 2px;\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                                     "      height: 14px;\n"
                                     "      subcontrol-position: bottom;\n"
                                     "      subcontrol-origin: margin;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::sub-line:vertical\n"
                                     "{\n"
                                     "      border: 1px solid #1b1b19;\n"
                                     "      border-radius: 2px;\n"
                                     "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
                                     "      height: 14px;\n"
                                     "      subcontrol-position: top;\n"
                                     "      subcontrol-origin: margin;\n"
                                     "}\n"
                                     "\n"
                                     "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                                     "{\n"
                                     "      border: 1px solid black;\n"
                                     "      width: 1px;\n"
                                     "      height: 1px;\n"
                                     "      background: white;\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                     "{\n"
                                     "      background: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit\n"
                                     "{\n"
                                     "    background-color: #242424;\n"
                                     "}\n"
                                     "\n"
                                     "QPlainTextEdit\n"
                                     "{\n"
                                     "    background-color: #242424;\n"
                                     "}\n"
                                     "\n"
                                     "QHeaderView::section\n"
                                     "{\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
                                     "    color: white;\n"
                                     "    padding-left: 4px;\n"
                                     "    border: 1px solid #6c6c6c;\n"
                                     "}\n"
                                     "\n"
                                     "QCheckBox:disabled\n"
                                     "{\n"
                                     "color: #414141;\n"
                                     "}\n"
                                     "\n"
                                     "QDockWidget::title\n"
                                     "{\n"
                                     "    text-align: center;\n"
                                     "    spacing: 3px; /* spacing between items in the tool bar */\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                                     "}\n"
                                     "\n"
                                     "QDockWidget::close-button, QDockWidget::float-button\n"
                                     "{\n"
                                     "    text-align: center;\n"
                                     "    spacing: 1px; /* spacing between items in the tool bar */\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                                     "}\n"
                                     "\n"
                                     "QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
                                     "{\n"
                                     "    background: #242424;\n"
                                     "}\n"
                                     "\n"
                                     "QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
                                     "{\n"
                                     "    padding: 1px -1px -1px 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QMainWindow::separator\n"
                                     "{\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                                     "    color: white;\n"
                                     "    padding-left: 4px;\n"
                                     "    border: 1px solid #4c4c4c;\n"
                                     "    spacing: 3px; /* spacing between items in the tool bar */\n"
                                     "}\n"
                                     "\n"
                                     "QMainWindow::separator:hover\n"
                                     "{\n"
                                     "\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
                                     "    color: white;\n"
                                     "    padding-left: 4px;\n"
                                     "    border: 1px solid #6c6c6c;\n"
                                     "    spacing: 3px; /* spacing between items in the tool bar */\n"
                                     "}\n"
                                     "\n"
                                     "QToolBar::handle\n"
                                     "{\n"
                                     "     spacing: 3px; /* spacing between items in the tool bar */\n"
                                     "     background: url(:/dark_orange/img/handle.png);\n"
                                     "}\n"
                                     "\n"
                                     "QMenu::separator\n"
                                     "{\n"
                                     "    height: 2px;\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                                     "    color: white;\n"
                                     "    padding-left: 4px;\n"
                                     "    margin-left: 10px;\n"
                                     "    margin-right: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QProgressBar\n"
                                     "{\n"
                                     "    border: 2px solid grey;\n"
                                     "    border-radius: 5px;\n"
                                     "    text-align: center;\n"
                                     "}\n"
                                     "\n"
                                     "QProgressBar::chunk\n"
                                     "{\n"
                                     "    background-color: #d7801a;\n"
                                     "    width: 2.15px;\n"
                                     "    margin: 0.5px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab {\n"
                                     "    color: #b1b1b1;\n"
                                     "    border: 1px solid #444;\n"
                                     "    border-bottom-style: none;\n"
                                     "    background-color: #323232;\n"
                                     "    padding-left: 10px;\n"
                                     "    padding-right: 10px;\n"
                                     "    padding-top: 3px;\n"
                                     "    padding-bottom: 2px;\n"
                                     "    margin-right: -1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::pane {\n"
                                     "    border: 1px solid #444;\n"
                                     "    top: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:last\n"
                                     "{\n"
                                     "    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
                                     "    border-top-right-radius: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:first:!selected\n"
                                     "{\n"
                                     " margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
                                     "\n"
                                     "\n"
                                     "    border-top-left-radius: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected\n"
                                     "{\n"
                                     "    color: #b1b1b1;\n"
                                     "    border-bottom-style: solid;\n"
                                     "    margin-top: 3px;\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected\n"
                                     "{\n"
                                     "    border-top-left-radius: 3px;\n"
                                     "    border-top-right-radius: 3px;\n"
                                     "    margin-bottom: 0px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected:hover\n"
                                     "{\n"
                                     "    /*border-top: 2px solid #ffaa00;\n"
                                     "    padding-bottom: 3px;*/\n"
                                     "    border-top-left-radius: 3px;\n"
                                     "    border-top-right-radius: 3px;\n"
                                     "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
                                     "}\n"
                                     "\n"
                                     "QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
                                     "    color: #b1b1b1;\n"
                                     "    background-color: #323232;\n"
                                     "    border: 1px solid #b1b1b1;\n"
                                     "    border-radius: 6px;\n"
                                     "}\n"
                                     "\n"
                                     "QRadioButton::indicator:checked\n"
                                     "{\n"
                                     "    background-color: qradialgradient(\n"
                                     "        cx: 0.5, cy: 0.5,\n"
                                     "        fx: 0.5, fy: 0.5,\n"
                                     "        radius: 1.0,\n"
                                     "        stop: 0.25 #ffaa00,\n"
                                     "        stop: 0.3 #323232\n"
                                     "    );\n"
                                     "}\n"
                                     "\n"
                                     "QCheckBox::indicator{\n"
                                     "    color: #b1b1b1;\n"
                                     "    background-color: #323232;\n"
                                     "    border: 1px solid #b1b1b1;\n"
                                     "    width: 9px;\n"
                                     "    height: 9px;\n"
                                     "}\n"
                                     "\n"
                                     "QRadioButton::indicator\n"
                                     "{\n"
                                     "    border-radius: 6px;\n"
                                     "}\n"
                                     "\n"
                                     "QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
                                     "{\n"
                                     "    border: 1px solid #ffaa00;\n"
                                     "}\n"
                                     "\n"
                                     "QCheckBox::indicator:checked\n"
                                     "{\n"
                                     "    image:url(:/dark_orange/img/checkbox.png);\n"
                                     "}\n"
                                     "\n"
                                     "QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
                                     "{\n"
                                     "    border: 1px solid #444;\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "QSlider::groove:horizontal {\n"
                                     "    border: 1px solid #3A3939;\n"
                                     "    height: 8px;\n"
                                     "    background: #201F1F;\n"
                                     "    margin: 2px 0;\n"
                                     "    border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QSlider::handle:horizontal {\n"
                                     "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                     "      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                                     "    border: 1px solid #3A3939;\n"
                                     "    width: 14px;\n"
                                     "    height: 14px;\n"
                                     "    margin: -4px 0;\n"
                                     "    border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QSlider::groove:vertical {\n"
                                     "    border: 1px solid #3A3939;\n"
                                     "    width: 8px;\n"
                                     "    background: #201F1F;\n"
                                     "    margin: 0 0px;\n"
                                     "    border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QSlider::handle:vertical {\n"
                                     "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
                                     "      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                                     "    border: 1px solid #3A3939;\n"
                                     "    width: 14px;\n"
                                     "    height: 14px;\n"
                                     "    margin: 0 -4px;\n"
                                     "    border-radius: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QAbstractSpinBox {\n"
                                     "    padding-top: 2px;\n"
                                     "    padding-bottom: 2px;\n"
                                     "    border: 1px solid darkgray;\n"
                                     "\n"
                                     "    border-radius: 2px;\n"
                                     "    min-width: 50px;\n"
                                     "}")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 120, 113, 20))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 170, 113, 20))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 270, 52, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 20))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 230, 113, 20))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 201, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 50, 111, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 121, 20))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(230, 110, 47, 20))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 47, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 47, 20))
        self.label_8.setObjectName("label_9")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(200, 135, 141, 31))
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 270, 75, 23))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(290, 110, 41, 21))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_3.setGeometry(QtCore.QRect(200, 160, 141, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 361, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.textBrowser_2.setPalette(palette)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter Start City"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Enter Goal City"))
        self.pushButton.setToolTip(_translate("Form", "Press To Search"))
        self.pushButton.setText(_translate("Form", "Run"))
        self.pushButton_2.setToolTip(_translate("Form", "Press To Close"))
        self.pushButton_2.setText(_translate("Form", "Close"))
        self.comboBox.setItemText(0, _translate("Form", "BFS"))
        self.comboBox.setItemText(1, _translate("Form", "BFS-2G"))
        self.comboBox.setItemText(2, _translate("Form", "DFS"))
        self.comboBox.setItemText(3, _translate("Form", "DFS-2G"))
        self.comboBox.setItemText(4, _translate("Form", "A* \"c->walking, h->aerial\""))
        self.comboBox.setItemText(5, _translate("Form", "A* \"c->car, h-> aerial or walking\""))
        self.label.setText(_translate("Form", "Select Search Algorithm:"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Enter Second Goal"))
        self.label_3.setText(_translate("Form", "Second Goal for \"BFS-2G & DFS-2G Algos\""))
        self.comboBox_2.setItemText(0, _translate("Form", "Aerial"))
        self.comboBox_2.setItemText(1, _translate("Form", "Walking"))
        self.label_2.setText(_translate("Form", "Select heurisitic:"))
        self.label_6.setText(_translate("Form", "Total Cost:"))
        self.label_5.setText(_translate("Form", "Start City"))
        self.label_8.setText(_translate("Form", "Goal City"))
        self.label_9.setText(_translate("Form", "Status:"))
        self.pushButton_3.setToolTip(_translate("Form", "Press To Search"))
        self.pushButton_3.setText(_translate("Form", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Mapping"))


ui = Ui_Form()

graphs = {}
optimalPath = []


def clicked():
    global graphs, optimalPath
    start = ui.lineEdit.text()
    goal = ui.lineEdit_2.text()
    secondGoal = ui.lineEdit_3.text()
    lt = ['0', '1', '2', '3', '4', '5', '6',
          '7', '8', '9', '10', '11', '12', '13', '14', '15', '16',
          '17', '18', '19']
    if (start or goal) == '':
        ui.textBrowser_3.setText("Please Enter Start And Goal")
    elif start not in lt or goal not in lt:
        ui.textBrowser_3.setText("Check mapping tap for info")
    else:
        ui.textBrowser_3.setText("")
        ui.textBrowser.setText("")

        graph = graphs = buildGraph()
        areal, walking = heuristic(int(start))
        algos = Algorithms
        algorithm = ui.comboBox.currentText()
        if algorithm == 'BFS':
            optimalPath = algos.bfs(graph, int(start), int(goal))[1]
            ui.textBrowser_3.setText("Search Succeeded")
        elif algorithm == 'BFS-2G':
            if secondGoal == '':
                ui.textBrowser_3.setText("Please Enter Second Goal")
            else:
                algos.bfs(graph, int(start), int(goal), int(secondGoal))
                ui.textBrowser_3.setText("Search Succeeded")
        elif algorithm == 'DFS':
            optimalPath = algos.dfs(graph, int(start), int(goal))[1]
            ui.textBrowser_3.setText("Search Succeeded")
        elif algorithm == 'DFS-2G':
            if secondGoal == '':
                ui.textBrowser_3.setText("Please Enter Second Goal")
            else:
                algos.dfs(graph, int(start), int(goal), int(secondGoal))
                ui.textBrowser_3.setText("Search Succeeded")
        elif algorithm == 'A* "c->car, h-> aerial or walking"':
            heu = ui.comboBox_2.currentText()
            if heu == 'Aerial':
                optimalPath, totalCost = algos.AStar(graph, areal, int(start), int(goal))
            else:
                optimalPath, totalCost = algos.AStar(graph, walking, int(start), int(goal))
            ui.textBrowser.setText(str(totalCost))
            ui.textBrowser_3.setText("Search Succeeded")
        else:
            data, graphs = algos.AStarWA(graph, heuristic(int(start)), int(start), int(goal))
            optimalPath = data[0]
            ui.textBrowser.setText(str(data[1]))
            ui.textBrowser_3.setText("Search Succeeded")


def plot():
    Plot.plotGraph(graphs, optimalPath)


def mapping():
    data = ""
    map = {0: "Aka", 1: "Bethlehem", 2: "Dura", 3: "Haifa", 4: "Halhoul", 5: "Hebron", 6: "Jenin", 7: "Jericho",
           8: "Jerusalem", 9: "Nablus",
           10: "Nazareth", 11: "Qalqilya", 12: "Ramallah", 13: "Ramleh", 14: "Sabastia", 15: "Safad", 16: "Salfit",
           17: "Tubas", 18: "Tulkarm", 19: "Yafa"}
    for key, item in map.items():
        data += str(key) + ' ' + str(item) + '\n'
    return data + "\nNOTE: Range of cities [0-19] don't choose smaller or bigger number."


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui.setupUi(Form)
    ui.pushButton.clicked.connect(clicked)
    ui.pushButton_3.clicked.connect(plot)
    ui.textBrowser_2.setText(mapping())
    Form.setWindowTitle("Search Algorithms for Route Navigation")
    Form.show()
    sys.exit(app.exec_())
